#!/bin/bash

h="$( ghc haskell >/dev/null 2>&1 && ./haskell )"
p="$( ./python.py )"
same=1

if ! diff <( printf '%s\n' "$h" ) <( printf '%s\n' "$p" ); then
  printf 'Haskell vs Python\n'
  same=0
fi

g="$(go run go.go)"
if ! diff <( printf '%s\n' "$h" ) <( printf '%s\n' "$g" ); then
  printf 'Haskell vs Go\n'
  same=0
fi

! (( same )) && exit 1

printf 'All same\n'

echo Haskell
time ./haskell >/dev/null
echo ---
echo Python
time ./python.py >/dev/null
echo ---
echo Go
time go run go.go >/dev/null
